<?php

namespace App\Models;
use App\Traits\ParseCreatedAt;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;
use  Illuminate\Support\Facades\Hash;
class User extends Authenticatable
{
    use Notifiable;
    use ParseCreatedAt;
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
    protected $fillable = [
        'name','username', 'avatar', 'password','email'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts(){
        return $this->hasMany(Post::class);
    }

    /*Hash password*/
    public function setPasswordAttribute($password){
        $this->attributes['password'] = Hash::make($password);
    }

    /*Insert link hình vào avatar của user*/
    public function setAvatarAttribute($link) {
        $this->attributes['avatar'] = $link;
    }

    public function likedThisPost(Post $post){
        $row = Like::where('user_id', $this->id)->where('post_id', $post->id)->first();
        if ($row){
            /*liked*/
            return $row;
        }
        /*Not like yet*/
        return false;
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleted(function($user) {
            foreach($user->posts as $post){
                DB::table("posts_tags")->where('post_id','=',$post->id)->delete();
                foreach ($post->comments as $comment) {
                    $comment->delete();
                }
                foreach ($post->likes as $like){
                    $like->delete();
                }
                $post->delete();
            }
        });
    }

}
